Vagrant.configure("2") do |config|
  config.vm.box = "centos/7"
  config.vm.box_version = "2004.01"
  config.vbguest.installer_options = { allow_kernel_upgrade: true }
  config.vm.synced_folder "./shared_folder", "/home/vagrant/"
end
