# Create a array of hash for 2 servers
servers = [
  {
    :server_hostname => "DATABASE01",
    :server_ip => "10.0.5.20",
    :server_function => "MYSQL",
    :server_box => "ubuntu/focal64"
  },
  {
    :server_hostname => "WEB01",
    :server_ip => "10.0.5.10",
    :server_function => "PHP",
    :server_box => "envimation/ubuntu-xenial"
  }
]

Vagrant.configure("2") do |config|
  servers.each do |server|
    config.vm.define server[:server_hostname] do |srv|
      srv.vm.box = server[:server_box]
      srv.vm.hostname = server[:server_hostname]
      srv.vm.network "private_network", ip: server[:server_ip]

      # Inline provision based on server function
      if server[:server_function] == "PHP"
        srv.vm.provision "shell", inline: <<-SHELL
          sudo apt-get update
          sudo apt-get install -y apache2 nano git
          sudo apt-get install -y php libapache2-mod-php php-mysql mysql-client iputils-ping
          sudo service apache2 restart
          sudo cd /var/www/html/
          sudo git clone https://github.com/ReC82/TinyPhpMysqlExample.git /var/www/html/TinyPhpMysqlExample
          sudo mv /var/www/html/TinyPhpMysqlExample/* /var/www/html/
          sudo sed -i 's/your_database/lab06/g' /var/www/html/db.sql
          sudo sed -i 's/lab05/lab06/g' /var/www/html/index.php
          mysql -h 10.0.5.20 -u vagrant -pvagrant < /var/www/html/db.sql
        SHELL
        srv.vm.provision "shell", inline: <<-SHELL
          echo "export MYSQL_DB=lab06" >> /home/vagrant/.bashrc
        SHELL
        srv.vm.network "forwarded_port", guest: 80, host: 8888, id: "http"
        srv.vm.provider :virtualbox do |vbox|
          vbox.customize ["modifyvm", :id, "--memory", 512]
          vbox.customize ["modifyvm", :id, "--cpus", 1]
        end
      elsif server[:server_function] == "MYSQL"
        srv.vm.provision "shell", path: "mysql_provision.sh"
        srv.vm.provision "shell", inline: <<-SHELL
          echo "export ENV_VAR_MYSQL=value_mysql" >> /home/vagrant/.bashrc
        SHELL
        srv.vm.provider :virtualbox do |vbox|
          vbox.customize ["modifyvm", :id, "--memory", 1024]
          vbox.customize ["modifyvm", :id, "--cpus", 1]
        end
      end
    end
  end
end
