# SERVER 1
HOST1_NAME = "Server1"
HOST1_BOX = "envimation/ubuntu-xenial"
HOST2_IP = "10.0.5.10"

# SERVER 2
HOST2_NAME = "Server2"
HOST2_BOX = "envimation/ubuntu-xenial"
HOST2_IP = "10.0.5.11"

Vagrant.configure("2") do |config|
  # SERVER 1
  config.vm.define HOST1_NAME do |host1|
    host1.vm.box = HOST1_BOX
    host1.vm.hostname = HOST1_NAME
    host1.vm.network "private_network", ip: HOST1_IP
  end

  # SERVER 2
  config.vm.define HOST2_NAME do |host2|
    host2.vm.box = HOST2_BOX
    host2.vm.hostname = HOST2_NAME
    host2.vm.network "private_network", ip: HOST2_IP
  end
end
