# Define the number of servers
num_servers = 3

# Initialize an empty array to store server configurations
servers = []

# Loop through to create server configurations
num_servers.times do |i|
  server_name = "Server#{i + 1}"
  server_ip = "10.0.5.#{i + 10}"  # Starting IP address from 10.0.5.10
  server_ssh_port = 2220 + i
  server_config = {
    name: server_name,
    box: "envimation/ubuntu-xenial",
    ip: server_ip,
    ssh_port: server_ssh_port
  }
  puts server_config
  servers << server_config  # Add server configuration to the array
end

Vagrant.configure("2") do |config|
  servers.each do |server|
    config.vm.define server[:name] do |srv|
      srv.vm.box = server[:box]
      srv.vm.hostname = server[:name]
      srv.vm.network "private_network", ip: server[:ip]
      srv.vm.network "forwarded_port", guest: 22, host: server[:ssh_port], id: "ssh"
    end
  end
end
